Set Leaflet icon path explicitly.
When we tried to deploy maps on staging, we got the following error
message in our Javascript console:

Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually.

... so we did. The end.